package es.unavarra.tlm.dscr_10.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOG".
 */
public class Log {

    private Long id;
    /** Not-null value. */
    private String nombre;
    /** Not-null value. */
    private java.util.Date acceso;

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, String nombre, java.util.Date acceso) {
        this.id = id;
        this.nombre = nombre;
        this.acceso = acceso;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Not-null value. */
    public java.util.Date getAcceso() {
        return acceso;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAcceso(java.util.Date acceso) {
        this.acceso = acceso;
    }

}
